# -*- coding: utf-8 -*-
"""SpatialAudio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1brQ46i6jYkt3emkw94tDl2WctVIglOWe
"""

import numpy as np
from scipy.signal import fftconvolve
from scipy.io import loadmat
import soundfile as sf
from IPython.display import Audio

"""Checking sampling rate,
change .mat to .wav
"""

sample, sr = sf.read("sample.wav")
print(sr)
if sample.ndim > 1:
    sample = sample[:, 0]

print(sample.shape)

Audio("sample.wav")

"""frontal = 0, 48, 98;;
final = 18, 54
"""

def audio_position(arr1, arr2, data1, data2):

  dict1 = {}
  dict2 = {}

  for i in range(len(arr1)+len(arr2)):

    if i < len(arr1):
      dict1[i] = {"left"+str(i): fftconvolve(sample, data1["left"][:, arr1[i]], mode="full")}
      dict2[i] = {"right"+str(i): fftconvolve(sample, data1["right"][:, arr1[i]], mode="full")}

    else:
      dict1[i] = {"left"+str(i): fftconvolve(sample, data2["left"][:, arr2[i-len(arr1)]], mode="full")}
      dict2[i] = {"right"+str(i): fftconvolve(sample, data2["right"][:, arr2[i-len(arr1)]], mode="full")}

  return dict1, dict2

# 角度（index）
horizontal = [18, 54]
frontal = [0, 48, 98]
data_horizontal = loadmat("large_pinna_final.mat")
data_frontal = loadmat("large_pinna_frontal.mat")

left, right = audio_position(horizontal, frontal, data_horizontal, data_frontal)

left_sum = 0
right_sum = 0
for i in range(len(left)):
  left_sum += left[i]["left"+str(i)]
  right_sum += right[i]["right"+str(i)]
# 合成後の最大値で割って、-1.0 ~ 1.0 の範囲に収める
max_val = np.max(np.abs([left_sum, right_sum]))
if max_val > 1:
    left_sum /= max_val * 0.8
    right_sum /= max_val * 0.8

stereo = np.vstack([left_sum, right_sum]).T
# 保存
sf.write("output.wav", stereo, sr)

Audio('output.wav')

def add_reflection(source, data_h, sr, reflect_idx, delay_ms=20, gain=0.4):
  delay_samples = int(sr * (delay_ms / 1000))
    # 遅延させた音源
  reflected_source = np.zeros(len(source) + delay_samples)
  reflected_source[delay_samples:] = source * gain

    # 反射音のHRTF適用
  reflect_l = fftconvolve(reflected_source, data_h["left"][:, reflect_idx], mode="full")
  reflect_r = fftconvolve(reflected_source, data_h["right"][:, reflect_idx], mode="full")
  return reflect_l, reflect_r

# 反射音を左右別々に作る
ref_r_l, ref_r_r = add_reflection(sample, data_horizontal, sr, reflect_idx=18, delay_ms=20)
ref_l_l, ref_l_r = add_reflection(sample, data_horizontal, sr, reflect_idx=54, delay_ms=25)

# Horizontalの反響音も作れるできるなら

# 音が何回も足されるからその分、割るか引くかして

# 全ての長さを揃えて足す
max_len = max(len(left_sum), len(ref_r_l), len(ref_l_l))

def pad(data, length):
    return np.pad(data, (0, length - len(data)), 'constant')

final_l = pad(left_sum, max_len) + pad(ref_r_l, max_len) + pad(ref_l_l, max_len)
final_r = pad(right_sum, max_len) + pad(ref_r_r, max_len) + pad(ref_l_r, max_len)

# --- 【超重要】パチパチ音を消す「正規化」 ---
audio_final = np.vstack([final_l, final_r]).T
peak = np.max(np.abs(audio_final))
if peak > 0:
    audio_final = audio_final / peak * 0.8 # 余裕を持って割る

# 保存
sf.write("bose_style.wav", audio_final, sr)

Audio('bose_style.wav')