[package]
name = "dsp-core"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.6", features = ["arch-cortex-m", "executor-thread"] }
embassy-rp = { version = "0.1", features = ["defmt", "rp2350a", "time-driver-pacing-timer"] }
embassy-time = "0.3"
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
cortex-m-rt = "0.7"

libm = "0.2"
microfft = "0.5"
